/**
 * Centralized route generation for InducksButBetter
 *
 * This module ensures that all URLs and internal links generated by the application
 * follow a consistent and maintainable structure.
 *
 * Usage:
 * import { routes } from "@/lib/routes";
 * const href = routes.issue("fr/PM  272");   // -> /countries/fr/PM/272
 */

import { splitIssueCode } from "./issueCode";

/**
 * Encodes one path segment.
 *
 * Spaces become `+` rather than `%20` so codes stay readable, and every route
 * helper uses this same function — a mismatch between two encoders made a
 * single click push two history entries.
 */
const encode = (str: string) => encodeURIComponent(str).replace(/%20/g, "+");

/** Joins already-meaningful segments, encoding each one but keeping the `/`. */
const segments = (...parts: string[]) => parts.filter(Boolean).map(encode).join("/");

export const routes = {
  // Main tabs
  home: () => `/home`,
  settings: () => `/settings`,
  suggestions: () => `/suggestions`,
  sql: () => `/sql`,

  // Entities
  story: (code: string) => `/stories/${encode(code)}`,
  character: (code: string) => `/characters/${encode(code)}`,
  author: (code: string) => `/authors/${encode(code)}`,
  publisher: (id: string) => `/publishers/${encode(id)}`,
  // Indexers get their own space: they catalogue issues, they do not create
  // stories, so an author page would describe the wrong contribution.
  indexer: (code: string) => `/indexers/${encode(code)}`,

  // Country hierarchy
  country: (code: string) => `/countries/${encode(code)}`,

  // Publications live under their country: /countries/de/LTB
  publication: (code: string) => `/countries/${segments(...code.split("/"))}`,

  /**
   * Issues extend the same hierarchy with the issue number:
   * /countries/de/LTB/613
   *
   * Pass the row's `publicationcode` when available — it makes the split
   * between publication code and issue number exact for the rare unpadded
   * codes whose issue number itself contains a space.
   */
  issue: (code: string, publicationcode?: string) => {
    const parts = splitIssueCode(code, publicationcode);
    if (!parts.issuenumber) return `/countries/${segments(...parts.publicationcode.split("/"))}`;
    return `/countries/${segments(...parts.publicationcode.split("/"), parts.issuenumber)}`;
  },
};
