/**
 * Centralized route generation for InducksButBetter
 * 
 * This module ensures that all URLs and internal links generated by the application
 * follow a consistent and maintainable structure.
 * 
 * Usage:
 * import { routes } from "@/lib/routes";
 * const href = routes.issue("fr/PM 123");
 */

const encode = (str: string) => encodeURIComponent(str).replace(/%20/g, "+");

export const routes = {
  // Main tabs
  home: () => `/home`,
  settings: () => `/settings`,
  suggestions: () => `/suggestions`,
  sql: () => `/sql`,
  
  // Entities
  story: (code: string) => `/stories/${encode(code)}`,
  character: (code: string) => `/characters/${encode(code)}`,
  author: (code: string) => `/authors/${encode(code)}`,
  publisher: (id: string) => `/publishers/${encode(id)}`,
  
  // Country hierarchy
  country: (code: string) => `/countries/${encode(code)}`,
  
  // Publications are now structured strictly under the countries path: /countries/de/LTB
  publication: (code: string) => `/countries/${encode(code)}`,
  
  // Issues replace the space with a slash to maintain the clean hierarchy: /countries/de/LTB/613
  // If there are other spaces (e.g., in the issue number), they will become +
  issue: (code: string) => `/countries/${encode(code.replace(" ", "/"))}`,
};
